version: "3.9"

services:
  database:
    image: postgres:16
    container_name: contract-api-database
    environment:
      POSTGRES_DB: contract_api_db
      POSTGRES_USER: contract_api_user
      POSTGRES_PASSWORD: contract_api_password
    ports:
      - "12000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: